spring:
  application:
    name: TaskSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskSystem
    username: postgres
    password: 4795895q
    driver-class-name: org.postgresql.Driver


  liquibase:
    enabled: true